<?php

use Illuminate\Database\Seeder;
use App\Brand;

class BrandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $brands = [
            
            "- No Manufacturer -",
            "2N",
            "3C DISTRIBUTORS",
            "3D",
            "A4TECH (XAVIERY)",
            "ACC",
            "ACER",
            "ACER (PSI)",
            "ACMI",
            "ACR",
            "ADL",
            "ADLIB",
            "ADMIRAL",
            "AERMOTOTR",
            "AIGLE",
            "AIWA",
            "AKAI",
            "AKARI (ACE)",
            "AKIRA",
            "ALPHA ANTENNA",
            "ALPHA STEEL",
            "ALPHAWOOD",
            "AMERICAN CHEF",
            "AMERICAN HOME",
            "AMERICAN MASTER",
            "AMITY LIGHTING",
            "AOC (ANSI)",
            "APC",
            "APPLE",
            "ARISTON",
            "ARISTON (CYA)",
            "ASAHI",
            "ASROCK",
            "ASTRA",
            "ASTRON",
            "ASUS",
            "B R CHUA",
            "BAOLE",
            "BAOLE",
            "BARON",
            "BELDEN",
            "BELLFLOWER",
            "BELLTONE",
            "BIO-CLEAR",
            "BLACK SWEET",
            "BONNI-RIVER",
            "BRAUN",
            "BROTHER",
            "BUMBLEBEE",
            "CAMEL",
            "CANON",
            "CARRIBEAN",
            "CARRIER",
            "CASIO",
            "CD-R KING",
            "CHALLENGER",
            "CHANGHONG",
            "CHUNLAN",
            "CIGNAL(SKYWORTH)",
            "CISCO",
            "CITIBEDS",
            "CLARI-TRADE",
            "CLC",
            "COBY",
            "COCO TECH",
            "COMFORT PLUS",
            "CONDURA",
            "CONDURA (CDI)",
            "CONDURA (MEGA SAVER)",
            "CONTINENTAL SALES",
            "COOLERMASTER",
            "CORPORATE GIVEAWAYS",
            "COSMOTECH",
            "CROWN",
            "D LINK",
            "DAEWOO",
            "DAHUA",
            "DAIKIN",
            "DAPHNEDALE",
            "DELL",
            "DEVANT",
            "DIFOHO",
            "DIGITRON",
            "DOWELL",
            "DURASTAR",
            "DURASTONE",
            "DYNAFLOW",
            "EASTFRONT",
            "EDGE",
            "ELECTROMATE",
            "ELEPHANT",
            "EMPYREAN",
            "EPSON",
            "ETHAN ALLEN",
            "EUREKA",
            "EUROTEK",
            "EV ELECTRONICS",
            "EVER HAUS",
            "EVEREST",
            "EXSOL",
            "EXSOL TRADING",
            "EXTENSIVE",
            "FANTECH",
            "FEDDERS",
            "FINE IMPRESSIONS",
            "FIREFLY",
            "FIREFLY (ACE)",
            "FIRST ASIA MOBILE",
            "FISHER & PAYKEL",
            "FLECO",
            "FLUKE(ACCESS)",
            "FLUKE(AWS)",
            "FORTIGATE",
            "FRANKE",
            "FSP EPSILON HEXA",
            "FUJIDENZO",
            "FUJITSU (INFOWORX)",
            "FUJIYAMA",
            "FUKUDA",
            "G-8",
            "GAISANO",
            "GALOCC",
            "GASCOLINE",
            "GASUL",
            "GE",
            "GEFORCE",
            "GENIUS",
            "GEOVISION",
            "GI PIPE",
            "GIMLY TRADING",
            "GIVEAWAYS",
            "GOLDEN COLLECTION",
            "GOLDSTAR",
            "GOLDTECH",
            "GOLS SAFE ROYAL",
            "GOULDEN MYERS",
            "GOULDS",
            "GPX PRODUCTS",
            "GREE",
            "HAIER",
            "HANABISHI",
            "HIKVISION",
            "HITACHI",
            "HOME TECH",
            "HOMEBEST",
            "HONDA",
            "HONEYWLL",
            "HOPE METAL",
            "HOT POINT",
            "HP",
            "HUAWEI",
            "HYUNDAI",
            "IBM",
            "iLuv",
            "IMARFLEX",
            "INDESIT",
            "INDESIT (CYA)",
            "INFINITE",
            "INFOMAX ENTERPRISE",
            "INFOWORX",
            "INNO3D",
            "INTEL",
            "INTERMEC",
            "IONA",
            "IRIDIUM(SAMSUNG)",
            "ISECURE",
            "ISECURENETWORKS INCORPORATED",
            "IWATA",
            "JELLA",
            "JENSHYL",
            "JML",
            "JOHNMATT",
            "JUST MOBILE",
            "JVC",
            "JVL",
            "KASSEL",
            "KATRINA CHUA",
            "KAWASAKI",
            "KELVINATOR",
            "KELVINATOR (CONCEPCION)",
            "KENGEN",
            "KENWOOD",
            "KEOSAN",
            "KING",
            "KING AIR",
            "KING KOIL",
            "KINGSTON",
            "KODAK",
            "KOLIN",
            "KOPPEL",
            "KYOWA",
            "LA GERMANIA",
            "LA Z BOY",
            "LABELLE",
            "LEDO",
            "LENOVO",
            "LENOVO (ANSI)",
            "LENOVO (PSI)",
            "LENOVO (THINK SERVER)",
            "LEXINGTON",
            "LG",
            "LG (TWIN MARK)",
            "LG(SMBR)",
            "LIMAX",
            "LOGITECH",
            "LUCKY HOME",
            "MABE",
            "MAGIC SING",
            "MAJESTIC",
            "MAKITA",
            "MANILA BED",
            "MARKSIGN CORPORATION",
            "MARUBISHI",
            "MARUSI",
            "MAR-VIN FURNITURES",
            "MARY LINE",
            "MATSUSHITA",
            "MBI",
            "MC DONALDS",
            "MEGA HOME",
            "MEGABOOM",
            "METROSHOPPERS TRADING",
            "M-GAS",
            "MICROSOFT",
            "MIDDLE EAST",
            "MIDEA",
            "MINAMI",
            "MODERN FURNITURE",
            "MONOTOP",
            "MOONHOUSE",
            "MSI",
            "MUEBLES",
            "NATIONAL",
            "NAVS",
            "NIKON",
            "NINTENDO",
            "NIPON",
            "NIPPON",
            "NOKIA",
            "NOVO",
            "NUMARK",
            "OFFICELUX",
            "OLYMPUS",
            "OMNI (ACE)",
            "OMNI (CLAIRE & GAB)",
            "OMNI (V.A.C)",
            "OPPO",
            "ORANGE",
            "ORTIGAS FURNITURE",
            "OSTER",
            "OSY",
            "OTHERS",
            "OZAKI",
            "PACOLINE",
            "PANASONIC",
            "PANDA",
            "PANDA (LFC)",
            "PAPOSPORT",
            "PENSONIC",
            "PHILACOR",
            "PHILAFLEX",
            "PHIL-DATA",
            "PHILIPPINE MULTI MEDIA",
            "PHILIPS",
            "PHILIPS (MULSON'S)",
            "PHILIPS K.A.",
            "PIONEER",
            "PLDT",
            "PLUVIAL",
            "POLAROID",
            "POLY SOUTH",
            "POWER ACE",
            "PRIMADONNA",
            "PRINT 2GO",
            "PRO DESIGN",
            "PROMAC",
            "Q & Q",
            "QUBE",
            "RAINBOW",
            "RAPOO (ANSI)",
            "RB FURNITURE",
            "REALME",
            "REGAIN",
            "RENAISSANCE",
            "RHINE RIVER",
            "RMV FURNICRAFT",
            "RUBY",
            "SAER",
            "SALEM",
            "SAMPLES",
            "SAMSUNG",
            "SAMSUNG(CELLPHONE)",
            "SAMSUNG(MSI-ECS)",
            "SANDISK",
            "SANLEY",
            "SANSIO",
            "SANSUI",
            "SANWA",
            "SANYO",
            "Sanyo - AQUA",
            "SCENIC",
            "SEARCH",
            "-Select Manufacturer-",
            "SELICON",
            "SEMICON",
            "SENNHEISER",
            "SEW AND ACCENT",
            "S-FINE",
            "SHARP",
            "SHOP VAC",
            "SIERRATON",
            "SILICON",
            "SILYA MESA",
            "SINGER",
            "SKYWORTH",
            "SKYWORTH (MULTIFOCUS)",
            "SMART",
            "SOCA",
            "SODEXO",
            "SOLID NARRA",
            "SONIC",
            "SONY",
            "SONY(MSI-ECS)",
            "STA ELENA",
            "STANDARD",
            "STANLEY",
            "STAR ASIA",
            "STUDIO5",
            "STYLE AND DECOR",
            "SUPREME",
            "SUTEKI",
            "SWELCO",
            "SYSCO",
            "TANK",
            "TARLAC RAIN GEAR",
            "TARP MO PRINT KO ATBP.",
            "TASHIN",
            "TCL",
            "TECHNOGAS",
            "TECHPOINT",
            "TECNOGAS",
            "TELECOM",
            "TOP DVD",
            "TOPSTAR",
            "TOSHIBA",
            "TOSHIBA(APPLIANCE)",
            "TRANSCEND",
            "TRI-M",
            "UNI-AIR",
            "UNICON",
            "UNIKON",
            "UNIKON",
            "UNIMAGNA",
            "UNION",
            "UNIQUE",
            "UNISPHERE",
            "UNIVET",
            "UR PERSONALIZED",
            "URDANETA MERCHANDISE",
            "UREKA STEEL",
            "VGM",
            "VITECH",
            "VIVO",
            "WANTAI",
            "WELLA",
            "WEST WOOD",
            "WHIRLPOOL",
            "WHITE WESTING HOUSE",
            "WINNER",
            "WINTIDE",
            "WOLF GUARD",
            "XCEL",
            "XTREME",
            "YOGA",     
         ];
 
 
         foreach ($brands as $brand) {
              Brand::create(['name' => $brand, 'active' => 'Y']);
         }
    }
}
