<?php

use Illuminate\Database\Seeder;
use App\ProductCategory;

class ProductCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $product_categories = [
            'ACCESSORIES',
            'ACCESS LICENSE',
            'ACCESSORIES',
            'ACCESSORRIES',
            'ACCESSSORIES',
            'ADAPTER',
            'AIR & WATER',
            'AIR CIRCULATOR',
            'AIR COOLER',
            'AIR CURTAIN',
            'AIR FRESHENER',
            'AIR FRYER',
            'AIR PURIFIER',
            'AIRCON',
            'AIRPOT',
            'ALARM',
            'ALARM SYSTEM',
            'AMPLIFIER',
            'ANALOG',
            'ANTENNA',
            'APC',
            'APC UPS',
            'APC UPS BATTERY',
            'AQUARIUM',
            'AREA RUG',
            'AUDIO',
            'AVAILABLE',
            'AVR',
            'BAG',
            'BAR COUNTER',
            'BAR SET',
            'BATHROOM SCALE',
            'BBQ GRILL',
            'BED',
            'BED BOX',
            'BED SET 6PCS',
            'BEDFRAME',
            'BEDFRAME w/ FOAM',
            'BEDROOM COLLECTION',
            'BEDROOM SET',
            'BENCH',
            'BIALETTI',
            'BIKE',
            'BIOMETRIC',
            'BLANC DISC',
            'BLANK DISC',
            'BLENDER',
            'BLUETOOTH',
            'BLUETOOTH/WIRELESS LAN',
            'BP MONITOR',
            'BREAD TOASTER',
            'BUFFALO DVD DRIVE',
            'BUILT-IN HOB',
            'BUILT-IN OVEN',
            'CABINET',
            'CABLE',
            'CABLE CONNECTOR',
            'CABLE WIRE',
            'CAMERA',
            'CANINET',
            'CARD',
            'CARD READER',
            'CART',
            'CASING',
            'CASSETTE',
            'CCTV',
            'CCTV CAMERA',
            'CCTV NETWORK VIDEO RECORDER',
            'CD PLAYER',
            'CD ROM',
            'CD WRITER',
            'CELLPHONE',
            'CHAIR',
            'CHILLER',
            'CHIPS',
            'CITRUS JUICER',
            'CLERICAL CHAIR',
            'CLIENT ACCESS LICENSE',
            'CLOCK',
            'CLOTHE HANGER',
            'COFFEE MAKER',
            'COFFEE SET',
            'COMPONENT',
            'COMPUTER INK',
            'COMPUTER SET',
            'CONNECTOR',
            'CONSOLE',
            'COOKER & WARMER',
            'COOKING SET',
            'COOKING WARE',
            'COOKWARE',
            'COOLER & WARMER',
            'COOLER JUG',
            'COOLING FAN',
            'COVER',
            'CPU',
            'CTV',
            'DECODER',
            'DEEP FRYER',
            'DESK',
            'DESKTOP',
            'DIGITAL COPIER',
            'DIGITAL VIDEO CASSETTE',
            'DINING CHAIR',
            'DINING SET',
            'DINING TOP',
            'DISH DRAWER',
            'DISH WASHER',
            'DISHDRAWER',
            'DISHWASHER',
            'DISK DRIVE',
            'DISKETTE',
            'DISPENSER',
            'DISPLAY CABINET',
            'DIVIDER',
            'DLINK',
            'DRESSER',
            'DRY IRON',
            'DRYER',
            'DVD COMPO CABLE',
            'DVD DRIVE',
            'DVD PLAYER',
            'DVD WRITER',
            'DVR',
            'EARPODS',
            'EGG BOILER',
            'ELECTRIC FAN',
            'ELECTRIC OVEN',
            'ELECTRIC RANGE',
            'EMERGENCY LIGHT',
            'ENTERTAINMENT RACK',
            'EXHAUST FAN',
            'EXTERNAL HBA',
            'EXTERNAL USB DVD',
            'FAN',
            'FAX MODEM',
            'FIBER CABLE',
            'FIRE EXTINGUISHER',
            'FIRE EXTINGUISHER HOOK',
            'FLAT IRON',
            'FLOWER',
            'FLOWER ARRANGEMENT',
            'FLOWER POT',
            'FOAM',
            'FOOD PROCESSOR',
            'FOOT SPA',
            'FOOTREST',
            'FORTIGATE',
            'FRAME',
            'FREE ITEMS',
            'FREE STANDING RANGE',
            'FREE STANDING STOVE',
            'FREEBIES',
            'FREEZER',
            'FRICTION RAIL',
            'FRY GRILL PAN',
            'FRYER',
            'GAME GADGET',
            'GAMING',
            'GARDEN SET',
            'GARMENT STEAMER',
            'GAS LIGHTERS',
            'GAS RANGE',
            'GENERATOR',
            'GIFT CHECK',
            'GIGABIT LAN',
            'GIVEAWAY',
            'GIVEAWAYS',
            'GRILL',
            'HAIR DRYER',
            'HARD DISK',
            'HARD DISK DRIVE',
            'HARD DISK ENCLOSURE',
            'HARD DRIVE',
            'HDD',
            'HDMI',
            'HEADPHONE',
            'HEADSET',
            'HEATER',
            'HOME AUDIO',
            'HOTDOG MAKER',
            'HUB',
            'ICE MAKER',
            'INDUCTION COOKER',
            'INFRARED ADAPTER',
            'INK',
            'INK CARTRIDGE',
            'INTERNAL FAX MODEM',
            'IPAD',
            'IPOD',
            'JUICE EXTRACTOR',
            'JUICE MIXER',
            'JUICE PRESERVER',
            'JUICER BLENDER',
            'KETTLE',
            'KEYBOARD',
            'KEYBOARD AND MOUSE',
            'KIT',
            'LABOR',
            'LAMP',
            'LAN CARD',
            'LAPTOP',
            'LAPTOP BAG',
            'LIGHT',
            'LINE CORD',
            'LINKSTATION',
            'LPG CLIPS',
            'LPG HOSE',
            'LPG REGULATOR',
            'MACHINE',
            'MAINTENANCE',
            'MAT',
            'MATTRESS',
            'MEDIA CENTER',
            'MEMORY',
            'MEMORY CARD',
            'MEMORY STICK',
            'MIC',
            'MICROPHONE',
            'MICROWAVE OVEN',
            'MIRROR',
            'MIXER',
            'MOBILE BATTERY',
            'MOBILE PEDESTAL',
            'MONITOR',
            'MOSQUITO KILLER',
            'MOTHERBOARD',
            'MOTORCYCLE',
            'MOUNTAIN BIKE',
            'MOUSE',
            'MP3',
            'MULTI V',
            'NETWORK CABLE',
            'NETWORK CABLES',
            'NETWORK EQUIPMENT',
            'NETWORK SWITCH',
            'NOTEBOOK',
            'NOVELTY ITEM',
            'NULL',
            'NVR',
            'OFFICE APPLICATION',
            'OFFICE AUDIO',
            'OFFICE HOME APPLICATION',
            'OPERATING SYSTEM',
            'OPTICAL DRIVES/CD ROM',
            'OTHERS',
            'OVEN',
            'OVEN TOASTER',
            'PALM TREE',
            'PANEL MULTIFUNCTION',
            'PARTITION',
            'PHONE',
            'PIE MAKER',
            'PILLOW',
            'PILLOW BLANKET',
            'PIPE',
            'PLAY STATION',
            'PLAYSTATION',
            'POE SPLITTER',
            'POE SWITCH',
            'PORT',
            'PORTABLE COOLER',
            'PORTABLE MUSIC PLAYER',
            'PORTABLE STATION',
            'PORTABLE USB 2.0',
            'POST',
            'POWER BANK',
            'POWER CORD',
            'POWER SUPPLY',
            'PRINTER',
            'PRINTER INK',
            'PROCESSOR',
            'PROJECTOR',
            'PUMP',
            'PURFIER',
            'PURIFIER',
            'RACK',
            'RACK PDU',
            'RANGEHOOD',
            'RDS CAL',
            'RECLINER',
            'REFRIGERATOR',
            'REGULATOR',
            'REMOTE',
            'REWINDER',
            'RIBBON',
            'ROCKING CHAIR',
            'ROPE',
            'ROUTER',
            'ROUTERS',
            'S-FRAME',
            'SANDWICH MAKER',
            'SAS CABLE',
            'SATTELITE',
            'SCANNER',
            'SENSOR',
            'SERVER',
            'SERVER CAL',
            'SERVER DEVICE',
            'SERVER RACK CABINET',
            'SERVICE ADAPTER',
            'SERVICES',
            'SEWING MACHINE',
            'SHIRT',
            'SHOWCASE',
            'SHREDDERS',
            'SIDE CAR',
            'SIDE RETURN',
            'SIGN',
            'SIM',
            'SIM CARD',
            'SLIP CASE',
            'SMOKE DETECTOR',
            'SOFA',
            'SOFA SET',
            'SOFTWARE',
            'SPEAKER',
            'SSD',
            'STAND',
            'STAND FAN',
            'STEAM IRON',
            'STEAM WIZARD',
            'STEAMER',
            'STOOL',
            'STORAGE',
            'STORAGE CABLE',
            'STORAGE DEVICE',
            'STORAGE DRIVE',
            'STORAGE ENCLOSURE',
            'STORAGE PART',
            'STOVE',
            'SUBWOOFER',
            'SUITE COLLECTION',
            'SUPPLY CHAIN',
            'SWITCH',
            'SWITCH NETWORK',
            'SWIVEL BASE',
            'SYSTEM UNIT',
            'TABLE',
            'TABLE & CHAIR',
            'TABLE GRILL',
            'TABLE OVEN',
            'TABLE TOP',
            'TABLE TOP LEG',
            'TABLET',
            'TABLEWARE UV STERILIZER',
            'TANK',
            'TAPE',
            'TAPE RECORDER',
            'TENT',
            'THERMO COOKER',
            'THERMOS',
            'THERMOSCAN',
            'THROW PILLOW CUSHION',
            'TONE GENERATOR',
            'TOOLS',
            'TRAVEL',
            'TRIPOD',
            'TROLLY',
            'TURBO BROILER',
            'TV BOX',
            'TV RACK',
            'TV TURNER',
            'TYPEWRITER',
            'UNIVERSAL REMOTE',
            'UPS',
            'USB-AC CHARGER',
            'USB-AS CHARGER',
            'USB',
            'USB HUB',
            'VACUUM',
            'VACUUM CLEANER',
            'VAULT',
            'VIDEO CARD',
            'VIDEO RECORDER',
            'WAFFLE MAKER',
            'WALKMAN',
            'WAN INTERFACE',
            'WASHING MACHINE',
            'WATER DISPENSER',
            'WATER PUMP',
            'WEB CAM',
            'WEBCAM',
            'WEIGHING SCALE',
            'WELDING MACHINE',
            'WIFI ROUTER',
            'WIFI TABLET',
            'WIRELESS HEADPHONE',
            'WIRELESS ROUTER',
            'WITCH',
            'WOODEN FRAME REST'
        ];

        foreach ($product_categories as $category) {
            ProductCategory::create(['name' => $category, 'active' => 'Y']);
        }
    }
}
